name: android_build

on:
  workflow_dispatch:

jobs:
  build_and_upload_apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
       # with:
          # 如果需要特定分支或tag，可以在这里指定
        # ref: ${{ github.ref }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17 # 更新到较新的LTS版本，可根据项目需求调整
          cache: 'gradle'

      - name: Retrieve Project Name
        id: get_project
        run: echo "::set-output name=PROJECT_NAME::$(cat project-to-build)"

      - name: Clone Project Repository
        run: git clone --depth=1 https://github.com/${{ github.repository }} ${{ steps.get_project.outputs.PROJECT_NAME }}

      - name: Grant Execute Permission to Gradle Wrapper
        working-directory: ${{ steps.get_project.outputs.PROJECT_NAME }}
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: ${{ steps.get_project.outputs.PROJECT_NAME }}
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK as Artifact
        if: ${{ always() }} # 即使构建失败也上传APK，便于调试
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: ${{ steps.get_project.outputs.PROJECT_NAME }}/app/build/outputs/apk/debug/*.apk
          retention-days: 7 # 自定义保留天数，根据需要调整
